on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate on Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy Cloud Function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v0.7.2
        with:
          name: v1
          runtime: go116
          project_id: nftcloner
          region: us-east1
          entry_point: Entrypoint
          env_vars: NFT_CONTRACT_ADDRESS=${{ secrets.NFT_CONTRACT_ADDRESS }},ETHEREUM_NODE_URL=${{ secrets.ETHEREUM_NODE_URL }}
          memory_mb: 128
          min_instances: 0
          max_instances: 2

      - name: Print URL
        run: 'echo "${{ steps.deploy.outputs.status }} ${{ steps.deploy.outputs.url }}"'